var services = {
	"A": "Alcohol workers",
	"AC": "Art classes",
	"AD": "Advocacy",
	"AH": "Accommodation advice",
	"B": "Barber",
	"BA": "Benefits advice",
	"BE": "Bedding available",
	"BS": "Bathroom/showers",
	"C": "Counselling",
	"CA": "Careers advice",
	"CL": "Clothing store",
	"D": "Drugs workers",
	"DA": "Debt advice",
	"DT": "Dentist",
	"ET": "Education and training",
	"F": "Food",
	"FF": "Free food",
	"FC": "Foot care",
	"IT": "Internet access",
	"L": "Laundry",
	"LA": "Legal advice",
	"LC": "Leisure activities",
	"LF": "Leisure facilities",
	"LS": "Luggage storage",
	"MD": "Music/drama",
	"MH": "Mental health",
	"MS": "Medical/health services",
	"NE": "Needle exchange",
	"OL": "Outreach worker links",
	"OW": "Outreach workers",
	"SH": "Sexual health advice",
	"TS": "Tenancy support"
}